# Food elements
FOOD_SIZE_X_Y = 40  # Pixels
FOOD_COLOR = (235, 33, 33)  # RGB: Red
FOOD_SCORE = 100  # Points

# Snake elements
SNAKE_SIZE_X_Y = 40  # Pixels
SNAKE_COLOR = (0, 204, 0)  # RGB: Green

# Display elements
DISPLAY_BACKGROUND_COLOR = (255, 255, 255)  # RGB: White
DISPLAY_HEIGHT = 800  # Pixels
DISPLAY_WIDTH = 800  # Pixels
DISPLAY_X_Y_COORDINATES = (DISPLAY_HEIGHT, DISPLAY_WIDTH)
GAME_FONT = "Arial"
GAME_FONT_SIZE = 20
MAX_DISPLAY_WIDTH = (DISPLAY_WIDTH // FOOD_SIZE_X_Y) - 1
MAX_DISPLAY_HEIGHT = (DISPLAY_HEIGHT // FOOD_SIZE_X_Y) - 1

# Game elements
FPS = 10  # Frames per second
CURRENT_SCORE_POS = (10, 10)
HIGH_SCORE_POSITION = (DISPLAY_WIDTH / 2, DISPLAY_HEIGHT / 2)
GAME_TEXT_COLOR = (0, 0, 0)  # RGB: Black
